name: validate
on:
  push:
    tags:
      - v*
    branches:
      - main
      - v*
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: install deps
      # Version of codespell bundled with Ubuntu is way old, so use pip.
      run: pip install codespell
    - name: run codespell
      run: codespell
