---
run:
  concurrency: 6
  deadline: 5m
linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - goconst
    - gofmt
    - goimports
    - goprintffuncname
    - interfacer
    - rowserrcheck
    - typecheck
  disable:
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godox
    - golint
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
