---

sudo: required

# N/B: host go env. not actually used, see .run_ci_tests.sh
language: go
go:
    - master

services:
  - docker

env:
    global:
        - TRAVIS_ENV="-e TRAVIS=$TRAVIS
                      -e CI=$CI
                      -e TRAVIS_COMMIT=$TRAVIS_COMMIT
                      -e TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
                      -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
                      -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
                      -e TRAVIS_PULL_REQUEST_SHA=$TRAVIS_PULL_REQUEST_SHA
                      -e TRAVIS_PULL_REQUEST_SLUG=$TRAVIS_PULL_REQUEST_SLUG
                      -e TRAVIS_BRANCH=$TRAVIS_BRANCH
                      -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID
                      -e TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"
    matrix:
        - GO_VERSION="stable"
        - GO_VERSION="1.9"
        - GO_VERSION="1.8"

before_install:
    - sudo apt-get -qq update

script:
    - echo "Travis/host environment:"
    - env
    - echo
    - echo "Running tests in SPC using ./.run_ci_tests.sh"
    - ./.run_ci_tests.sh
