---

testing_task:

  env:
    GOPATH: "/go"
    CIRRUS_WORKING_DIR: "${GOPATH}/src/github.com/containers/common"
    GOSRC: "$CIRRUS_WORKING_DIR"

  container:
    image: "registry.fedoraproject.org/fedora:34"
    cpu: 2
    memory: 2

  test_script:
    - dnf install -y go containers-common device-mapper-devel libseccomp-devel btrfs-progs-devel
    - make vendor
    - make build
    - make install.tools
    - make validate
    - make test


success_task:

    # This task is a required-pass in github settings,
    # it blocks PRs from merging if a depends_on task fails
    only_if: $CIRRUS_BRANCH != $DEST_BRANCH

    # ignores any dependent task conditions
    depends_on:
        - "testing"

    container:
        # Note: Image has dual purpose, see contrib/gate/README.md
        image: "quay.io/libpod/gate:master"
        cpu: 1
        memory: 1

