---
run:
  build-tags:
    - apparmor
    - seccomp
    - selinux
    - systemd
    - exclude_graphdriver_btrfs
    - containers_image_openpgp
    - cni
  timeout: 5m
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gofumpt
    - goprintffuncname
    - gosmopolitan
    - iface
    - intrange
    - makezero
    - mirror
    - misspell
    - nilnesserr
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
  gocyclo:
    min-complexity: 35
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  revive:
    rules:
      - name: dot-imports
        disabled: true

issues:
    # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - perfsprint
    # Exclude "should pass the context parameter" for libimage.LookupImage because of backward compatibility.
    - path: "libimage"
      text: "LookupImage"
      linters:
        - contextcheck
